In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r'D:\project_task_extra\Project\food\food_delivery\artifact\data_ingestion\2023-05-02-11-32-44\raw_data\finalTrain.csv')
df.shape

(45584, 20)

In [6]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [7]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [16]:
df['City'].unique()

array(['Metropolitian', 'Urban', 'Semi-Urban', nan], dtype=object)

:

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  object
 1   Delivery_person_ID           45584 non-null  object
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  object
 9   Time_Orderd                  43853 non-null  object
 10  Time_Order_picked            45584 non-null  object
 11  Weather_conditions           44968 non-null  object
 12  Road_traffic_density         44983 non-null  object
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  object
 15  Type_of_vehicle              45584 non-null  object
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  object
 18  City                         44384 non-null  object
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 7.0+ MB

array(['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny', nan],
      dtype=object)

In [ ]:
from geopy.distance import geodesic

In [34]:
df.isna().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [35]:
df['Time_Orderd_new'] = np.where(df['Time_Orderd'].str.contains('\.'),df['Time_Orderd'],np.nan)
df['Time_Orderd_new'] = df['Time_Orderd_new'].astype(float)
df['Time_Orderd_new'] = df['Time_Orderd_new'] * 86400
df['Time_Orderd_new'] =  pd.to_datetime(df['Time_Orderd_new'],unit='m')
df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'],format = '%H:%M',errors='coerce')
df['Time_Orderd'] = np.where((df['Time_Orderd_new'].isna()==False),df['Time_Orderd_new'],df['Time_Orderd'])
df.drop('Time_Orderd_new',axis=1)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,1900-01-01 21:55:00,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,1900-01-01 14:55:00,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,1900-01-01 17:30:00,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,1900-01-01 09:20:00,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,1900-01-01 19:50:00,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,1900-01-01 11:35:00,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,1900-01-01 19:55:00,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,1900-01-01 23:50:00,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,1900-01-01 13:35:00,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,1900-01-01 17:10:00,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [36]:
df['Time_Order_picked_new'] = np.where(df['Time_Order_picked'].str.contains('\.'),df['Time_Order_picked'],np.nan)
df['Time_Order_picked_new'] = df['Time_Order_picked_new'].astype(float)
df['Time_Order_picked_new'] = df['Time_Order_picked_new'] * 86400
df['Time_Order_picked_new'] =  pd.to_datetime(df['Time_Order_picked_new'],unit='m')
df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'],format = '%H:%M',errors='coerce')
df['Time_Order_picked'] = np.where((df['Time_Order_picked_new'].isna()==False),df['Time_Order_picked_new'],df['Time_Order_picked'])
df.drop('Time_Order_picked_new',axis=1)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Time_Orderd_new
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,1900-01-01 21:55:00,...,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,NaT
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,1900-01-01 14:55:00,...,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,NaT
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,1900-01-01 17:30:00,...,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,NaT
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,1900-01-01 09:20:00,...,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,NaT
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,1900-01-01 19:50:00,...,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,1900-01-01 11:35:00,...,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,NaT
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,1900-01-01 19:55:00,...,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36,NaT
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,1900-01-01 23:50:00,...,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,NaT
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,1900-01-01 13:35:00,...,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,NaT
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,1900-01-01 17:10:00,...,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,NaT

In [8]:
df.isna().sum()

ID                                 0
Delivery_person_ID                 0
Delivery_person_Age             1854
Delivery_person_Ratings         1908
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                     2161
Time_Order_picked                  0
Weather_conditions               616
Road_traffic_density             601
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries              993
Festival                         228
City                            1200
Time_taken (min)                   0
Time_Orderd_new                41946
dtype: int64

In [ ]:
df['Tim']

In [9]:
df['Time_Orderd'] = np.where((df['Time_Orderd_new'].isna()==False),df['Time_Orderd_new'],df['Time_Orderd'])

In [108]:
# df[['Time_Orderd','Time_Orderd_new']] = pd.to_datetime(df[['Time_Orderd','Time_Orderd_new']],format='%H:%M')

In [109]:
df[['Time_Orderd_new','Time_Orderd']].isna().sum()

Time_Orderd_new    41946
Time_Orderd         2161
dtype: int64

In [110]:
df[df['Time_Orderd_new'].isna()==False][['Time_Orderd_new','Time_Orderd']]

                 Time_Orderd_new                Time_Orderd
28    1970-01-28 11:59:59.998272 1970-01-28 11:59:59.998272
31    1970-02-27 11:59:59.998272 1970-02-27 11:59:59.998272
38    1970-02-17 12:00:00.001728 1970-02-17 12:00:00.001728
71    1970-02-22 12:00:00.000000 1970-02-22 12:00:00.000000
83    1970-02-27 11:59:59.998272 1970-02-27 11:59:59.998272
...                          ...                        ...
45457 1970-02-27 11:59:59.998272 1970-02-27 11:59:59.998272
45473 1970-02-25 00:00:00.001728 1970-02-25 00:00:00.001728
45544 1970-02-02 12:00:00.001728 1970-02-02 12:00:00.001728
45545 1970-01-26 00:00:00.001728 1970-01-26 00:00:00.001728
45573 1970-01-23 12:00:00.000000 1970-01-23 12:00:00.000000

[3638 rows x 2 columns]

In [111]:
df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'],format = '%H:%M',errors='coerce')
# df['Time_Orderd'] = df['Time_Orderd'].dt.strftime('%H:%M')
df['Time_Orderd'].isna().sum()

# extract hours and minutes and format as %H:%M
# df['time_format'] = df['time_format'].dt.strftime('%H:%M')

2161

In [112]:
df[df['Time_Order_picked'].str.contains('\.')==True]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Time_Orderd_new
36,0xc644,KOLRES16DEL02,37.0,4.9,22.539129,88.365507,22.559129,88.385507,13-02-2022,1900-01-01 10:55:00,...,Fog,Low,1,Snack,scooter,1.0,No,Urban,16,NaT
46,0x272d,COIMBRES07DEL03,24.0,4.7,10.961850,76.971082,11.051850,77.061082,10-03-2022,1900-01-01 17:55:00,...,Sunny,Medium,0,Buffet,motorcycle,0.0,No,Urban,19,NaT
47,0xddc5,AGRRES12DEL03,39.0,4.6,27.165108,78.015053,27.255108,78.105053,14-02-2022,1900-01-01 22:45:00,...,Sunny,Low,1,Snack,motorcycle,1.0,No,Metropolitian,27,NaT
52,0xb55a,MYSRES04DEL03,33.0,4.9,12.308500,76.665808,12.338500,76.695808,30-03-2022,1900-01-01 21:55:00,...,Sunny,Jam,2,Drinks,scooter,0.0,No,Metropolitian,22,NaT
57,0xde72,DEHRES19DEL02,39.0,4.9,30.372202,78.077151,30.422202,78.127151,15-02-2022,1900-01-01 20:55:00,...,Stormy,Jam,2,Meal,motorcycle,1.0,No,Metropolitian,30,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45499,0x426b,HYDRES06DEL01,NaN,NaN,17.455894,78.375467,17.525894,78.445467,23-03-2022,1900-01-01 17:55:00,...,Fog,Medium,0,Meal,motorcycle,1.0,No,Urban,36,NaT
45530,0x1180,JAPRES04DEL02,24.0,5.0,26.902328,75.794257,26.952328,75.844257,19-03-2022,1900-01-01 20:50:00,...,Stormy,Jam,1,Meal,scooter,1.0,No,Metropolitian,28,NaT
45538,0xcdd4,GOARES20DEL02,37.0,4.3,0.000000,0.000000,0.020000,0.020000,15-02-2022,1900-01-01 10:45:00,...,Windy,Low,0,Snack,motorcycle,0.0,No,Metropolitian,32,NaT
45566,0x91d5,HYDRES03DEL03,34.0,4.9,17.422819,78.449578,17.482819,78.509578,24-03-2022,1900-01-01 21:45:00,...,Stormy,Jam,1,Meal,motorcycle,1.0,No,Metropolitian,28,NaT
45577,0x4e21,BANGRES16DEL03,28.0,4.9,13.029198,77.570997,13.059198,77.600997,30-03-2022,1900-01-01 21:55:00,...,Sandstorms,Jam,1,Meal,scooter,1.0,No,Metropolitian,29,NaT

In [113]:
df[df['Time_Orderd'].str.contains('\.')==True]

AttributeError: Can only use .str accessor with string values!

In [114]:
df['Time_Orderd'] = np.where(df['Time_Orderd'].str.contains('\.'),pd.to_timedelta(df['Time_Orderd'] * 24, unit='h'),df['Time_Orderd'])
df['Time_Order_picked'] = np.where(df['Time_Order_picked'].str.contains('\.'),pd.to_timedelta(df['Time_Order_picked'] * 24, unit='h'),df['Time_Order_picked'])

AttributeError: Can only use .str accessor with string values!

In [115]:
df['Time_Orderd'] = df['Time_Orderd'].apply(lambda x: pd.to_datetime(x * 24 * 3600, unit='s').strftime('%H:%M') if isinstance(x, float) else x)
df['Time_Order_picked'] = df['Time_Order_picked'].apply(lambda x: pd.to_datetime(x * 24 * 3600, unit='s').strftime('%H:%M') if isinstance(x, float) else x)

In [116]:
df['Time_Orderd_tf'].value_counts()

KeyError: 'Time_Orderd_tf'

In [61]:
df['Time_Orderd_tf'] = np.where(df['Time_Orderd'].str.contains('\.'),pd.to_datetime(df['Time_Orderd']*24 ),df['Time_Orderd'])

# df['Time_Order_picked'] = df['Time_Order_picked'].apply(lambda x: pd.to_datetime(x * 24 * 3600, unit='s').strftime('%H:%M') if isinstance(x, float) and not np.isnan(x) else x)

ParserError: Unknown string format: 21:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:5521:55

In [46]:
df[df['Time_Orderd'].str.contains('\.')==True]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
28,0x6531,SURRES08DEL01,20.0,4.8,21.173343,72.792731,21.183343,72.802731,30-03-2022,0.458333333,11:10,Sandstorms,Low,2,Meal,scooter,1.0,No,Metropolitian,19
31,0x9b18,BANGRES17DEL01,22.0,4.8,12.972532,77.608179,13.042532,77.678179,18-03-2022,0.958333333,23:10,Fog,Low,1,Snack,motorcycle,1.0,No,Metropolitian,28
38,0x63b6,BANGRES05DEL03,27.0,4.9,12.970324,77.645748,13.030324,77.705748,19-03-2022,0.791666667,19:15,Windy,Medium,1,Drinks,scooter,1.0,No,Metropolitian,25
71,0x903a,BANGRES11DEL01,27.0,4.7,12.934365,77.616155,13.044365,77.726155,10-03-2022,0.875,21:15,Cloudy,Jam,2,Snack,scooter,1.0,No,Metropolitian,42
83,0xc042,AGRRES010DEL01,34.0,4.7,-27.163303,78.057044,27.233303,78.127044,16-02-2022,0.958333333,23:05,Sandstorms,Low,1,Drinks,scooter,0.0,No,Metropolitian,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45457,0xd6d8,GOARES11DEL02,24.0,4.8,15.544419,73.755736,15.674419,73.885736,18-02-2022,0.958333333,23:10,Stormy,Low,1,Meal,scooter,1.0,No,Urban,17
45473,0x6ecf,RANCHIRES010DEL03,20.0,5.0,23.354422,85.332900,23.444422,85.422900,08-03-2022,0.916666667,22:05,Fog,Jam,1,Drinks,scooter,1.0,No,Metropolitian,41
45544,0x46b6,PUNERES03DEL01,36.0,4.9,18.554382,73.798206,18.594382,73.838206,26-03-2022,0.541666667,13:10,Windy,High,2,Drinks,scooter,0.0,No,Metropolitian,28
45545,0x6607,COIMBRES16DEL02,26.0,4.2,11.010375,76.952950,11.030375,76.972950,01-04-2022,0.416666667,10:10,Windy,Low,0,Drinks,motorcycle,1.0,No,Urban,18
45573,0x59ae,PUNERES13DEL02,30.0,4.6,18.562450,73.916619,18.582450,73.936619,01-04-2022,0.375,09:15,Cloudy,Low,0,Meal,motorcycle,0.0,No,Metropolitian,20

In [41]:
df.loc[48,'Time_Orderd']

'20:35'

In [39]:
df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'],format='%H:%M')
df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'],format='%H:%M')

df['Time_Orderd'] = np.where(df['Time_Orderd'].isnull(), df['Time_Order_picked'] - pd.Timedelta(minutes=15), df['Time_Orderd'])

ValueError: time data '0.458333333' does not match format '%H:%M' (match)

In [2]:
import os
import sys
import requests
from six.moves import urllib
import tarfile
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedShuffleSplit, train_test_split

from food_delivery.logger import logging
from food_delivery.exception import CustomException

from food_delivery.entity.config_entity import DataIngestionConfig
from food_delivery.config.configuration import Configuration
from food_delivery.entity.artifact_entity import DataIngestionArtifact
from food_delivery.constant import *

In [18]:
class DataIngestion:

    def __init__(self, data_ingestion_config: DataIngestionConfig):
        """
        This is a constructor function that initializes a class object with a data ingestion
        configuration and logs any errors that occur.

        :param data_ingestion_config: The parameter `data_ingestion_config` is an instance of the
        `DataIngestionConfig` class, which contains configuration information for data ingestion. This
        parameter is passed to the constructor of a class that is being initialized
        :type data_ingestion_config: DataIngestionConfig
        """
        try:
            logging.info(
                f"\n\n{'='*20} Data Ingestion log Started {'='*20}\n\n")
            self.data_ingestion_config = data_ingestion_config

        except Exception as e:
            logging.info(f"Error Occurred at {CustomException(e,sys)}")
            raise CustomException(e, sys)

    def download_food_delivery_data(self,) -> str:
        """
        It downloads the food_delivery data from the remote url and stores it in the local file system
        :return: The file path of the downloaded file.
        """
        try:
            # extraction remote url to download url
            download_url = self.data_ingestion_config.dataset_download_url

            # folder location to download file
            tgz_download_dir = self.data_ingestion_config.tgz_download_dir

            os.makedirs(tgz_download_dir, exist_ok=True)

            food_delivery_file_name = os.path.basename(download_url)

            tgz_file_path = os.path.join(
                tgz_download_dir, food_delivery_file_name)

            logging.info(f"""
             --> Started Downloading......
             --> From URL : [{download_url}]
             --> Into Folder : [{tgz_file_path}]
             """)

            urllib.request.urlretrieve(download_url, tgz_file_path)

            # response = requests.get(download_url)
            # with open(tgz_file_path, 'wb') as f:
            #     f.write(response.content)

            logging.info(
                f"File :[{tgz_file_path}] has been downloaded successfully.")

            return tgz_file_path

        except Exception as e:
            logging.info(f"Error Occurred at {CustomException(e,sys)}")
            raise CustomException(e, sys)
        
    
    def extract_tgz_file(self, tgz_file_path: str):
        """
        It extracts the contents of a tgz file to a directory

        :param tgz_file_path: The path to the tgz file that you want to extract
        :type tgz_file_path: str
        """
        try:
            raw_data_dir = self.data_ingestion_config.raw_data_dir

            if os.path.exists(raw_data_dir):
                os.remove(raw_data_dir)

            logging.info(f"""
            --> Extracting Data from tgz file :  [{tgz_file_path}]
            --> to raw data dir : [{raw_data_dir}]
            """)

            os.makedirs(raw_data_dir, exist_ok=True)

            with tarfile.open(tgz_file_path) as food_delivery_tgz_file_obj:
                food_delivery_tgz_file_obj.extractall(path=raw_data_dir)
                
            return raw_data_dir

        except Exception as e:
            logging.info(f"Error Occurred at {CustomException(e,sys)}")
            raise CustomException(e, sys)
        
    def split_data_as_train_test(self,) -> DataIngestionArtifact:
        """
        It reads the data from the raw data directory, splits the data into train and test, and writes
        the train and test data into the ingested train and test directories
        :return: DataIngestionArtifact
        """
        try:

            raw_data_dir = self.data_ingestion_config.raw_data_dir

            file_name = os.listdir(raw_data_dir)[0]

            food_delivery_file_path = os.path.join(raw_data_dir, file_name)

            food_delivery_data_frame = pd.read_csv(food_delivery_file_path)

            logging.info(f'Reading file data from [{food_delivery_file_path}]')
            
            logging.info(f'Splitting Data into Train Test')
            df = None
            start_test_set = None
            X = food_delivery_data_frame.drop('Time_taken (min)', axis=1)
            
            y = food_delivery_data_frame['Time_taken (min)']
            df, start_test_set,df['Time_taken (min)'],start_test_set['Time_taken (min)'] = train_test_split(
                X,y ,test_size=0.2, random_state=42, stratify=y)

            train_file_path = os.path.join(
                self.data_ingestion_config.ingested_train_dir, file_name)
            test_file_path = os.path.join(
                self.data_ingestion_config.ingested_test_dir, file_name)

            if df is not None:
                os.makedirs(
                    self.data_ingestion_config.ingested_train_dir, exist_ok=True)
                logging.info(
                    f'Exporting training Dataset into [{train_file_path}]')
                df.to_csv(train_file_path, index=False)

            if start_test_set is not None:
                os.makedirs(
                    self.data_ingestion_config.ingested_test_dir, exist_ok=True)
                logging.info(
                    f'Exporting testing Dataset into [{test_file_path}]')
                start_test_set.to_csv(test_file_path, index=False)

            data_ingestion_artifact = DataIngestionArtifact(train_file_path=train_file_path,
                                                            test_file_path=test_file_path,
                                                            is_ingested=True,
                                                            message=f"Data Ingestion Completed Successefully")

            logging.info(
                f'Data Ingestion Artifact : [{data_ingestion_artifact}]')

            return data_ingestion_artifact

        except Exception as e:
            logging.info(f"Error Occurred at {CustomException(e,sys)}")
            raise CustomException(e, sys)

In [10]:
b = Configuration(config_file_path='D:\End_to_End_Project\Food_delivery\config\config.yaml')

In [19]:
a =DataIngestion(data_ingestion_config=b.get_data_ingestion_config())

In [21]:
tgz_path  = a.download_food_delivery_data()
raw_dir = a.extract_tgz_file(tgz_path)
print(raw_dir)
art = a.split_data_as_train_test(raw_dir)

CustomException: Python Script :
    [C:\Users\viral\AppData\Local\Temp\ipykernel_37488\319541822.py]
    at try block line number : [74] and exception block line no : [90]
    error message :
    [[WinError 5] Access is denied: 'd:\\End_to_End_Project\\Food_delivery\\notebook\\food_delivery\\artifact\\data_ingestion\\2023-04-26-20-54-34\\raw_data']